FROM python:2.7
RUN apt-get update && \
      apt-get -y install sudo

RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget \
    && apt-get clean

RUN sudo apt-get install libgsl-dev -y

RUN sudo apt-get install swig -y

RUN apt-get install libtool-bin

# # Install miniconda
# ENV CONDA_DIR /opt/conda
# RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
#     /bin/bash ~/miniconda.sh -b -p /opt/conda

# # Put conda in path so we can use conda activate
# ENV PATH=$CONDA_DIR/bin:$PATH

# RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo

# RUN conda create -n py2 python=2.7 -y

USER root
CMD /bin/bash